# Generated by Django 4.2 on 2023-05-29 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_profile_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Please enter 10 digits', regex='^\\+?1?\\d{10}$')]),
        ),
    ]
