# Generated by Django 4.2 on 2023-05-29 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_profile_age_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Please enter your correct age.'), django.core.validators.MaxValueValidator(150, message='Please enter your correct age.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='please enter 10 digit phone number', regex='^\\d{10}$')]),
        ),
    ]
